#! /bin/bash

###############################################
# INIT PARAMS
###############################################

# Import env variables:
if [ -f $PWD/.env ]; then
  source .env
else
  echo "No .env file found!!!"
  return 1
fi

# Require an argument
if [[ -z $1 ]]; then
  echo "You must supply a version number/name for the build to be deployed!"
  exit 1
fi

###############################################
# CONFIRM VERSION NAME TO BE DEPLOYED
###############################################
clear
echo -e """\033[32m
====================================================================
Are you sure you want to build and deploy the checked-out branch to:

https://$LINUX_HOST/$1

Type '\033[31myes\033[32m' to continue.

====================================================================
\033[0m"""

read decision
if [[ $decision != yes ]]; then
  echo "Cancelling."
  exit 0
fi

###############################################
# BUILD PAGES FOR REMOTE LINUX
###############################################

optional_prefix=/catch-gui

# First argument is name of output dist and final extension
# Second argument is optional prefix
./_build_client $1 $optional_prefix

if [[ $? != 0 ]]; then
  echo -e "Cancelling deployment to linux server."
fi

###############################################
# DEPLOY TO REMOTE LINUX
###############################################

echo -e """\033[32m
=============================================================
DEPLOYING BUNDLES TO: \033[0m https://$LINUX_HOST/$optional_prefix/$1 \033[32m
=============================================================
\033[0m"""

# RSYNC BUILD TO LINUX DEPLOYMENT
cmd="rsync -avzd $PWD/dist-linux/ $LINUX_USER@$LINUX_HOST:$LINUX_CATCH_GUI_PATH/$1"
eval $cmd
echo $cmd
cmd="rsync -avzd $PWD/dist-linux/ $LINUX_USER@$LINUX_HOST:$LINUX_CATCH_GUI_PATH/latest"
eval $cmd
echo $cmd

echo -e """\033[32m
==========================================================
Done. Your page has been deployed to: \033[0m
https://$LINUX_HOST$optional_prefix/$1 \033[32m
==========================================================
\033[0m"""
