#! /bin/bash

clear

# Ensure the terraform dirs have been initialized
if [[ ! -d .terraform ]]; then
  terraform init tf_scripts
fi

# Define pause-messaging function
function pause_before_next_stage() {
  echo -e """
    =======================================
    READY FOR NEXT STAGE: ${1}

    \033[32mNow is a safe time to quit.\033[0m
    \033[31mDo NOT quit while terraform is running!\033[0m

    Press Enter to Continue
    Press ctrl+c to Quit

    =======================================
"""
  read
  clear
}

###########################
# Terraform mini-pipeline #
###########################

# Make env vars available to
source .env

# Plan
pause_before_next_stage "terraform plan"
terraform plan tf_scripts

# Apply
pause_before_next_stage "terraform apply"
terraform apply tf_scripts
